name: Publish Package to npmjs
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Extract tag name
        id: extract
        run: echo "version=${GITHUB_REF#refs/tags/}" >> "${GITHUB_OUTPUT}"

      - name: Write npm version
        run: |
          new_version="${{ steps.extract.outputs.version }}"
          jq --arg new_version "$new_version" '.version = $new_version' package.json > temp.json && mv temp.json package.json

      - run: bun install

      - run: bun run build

      - uses: actions/setup-node@v3
        with:
          registry-url: "https://registry.npmjs.org"

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
